const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[character]));
const appUrl = process.env.APP_URL || process.env.CLIENT_URL?.split(",")[0] || "http://localhost:5173";
const brand = process.env.EMAIL_FROM_NAME || "KaintLook";

const layout = (title, content) => `<!doctype html><html><body style="margin:0;background:#f5f7fb;font-family:Arial,sans-serif;color:#202124;"><div style="max-width:620px;margin:24px auto;background:#fff;border:1px solid #e5e7eb;border-radius:12px;overflow:hidden;"><header style="background:#1b1b1b;padding:22px 28px;color:#fff;font-size:24px;font-weight:700;">${escapeHtml(brand)}</header><main style="padding:28px;"><h1 style="font-size:24px;margin:0 0 18px;color:#1b1b1b;">${escapeHtml(title)}</h1>${content}</main><footer style="padding:20px 28px;background:#fafafa;border-top:1px solid #eee;color:#6b7280;font-size:12px;line-height:1.6;">This is an automated message from ${escapeHtml(brand)}.<br/>Need help? ${escapeHtml(process.env.SUPPORT_EMAIL || process.env.EMAIL_USER || "Contact our support team")}<br/><a href="${escapeHtml(appUrl)}" style="color:#2575FC;">Visit ${escapeHtml(brand)}</a></footer></div></body></html>`;
const button = (label, url) => `<a href="${escapeHtml(url)}" style="display:inline-block;background:#2575FC;color:#fff;text-decoration:none;padding:12px 18px;border-radius:6px;font-weight:700;margin:8px 8px 8px 0;">${escapeHtml(label)}</a>`;
const orderCode = (order) => order._id.toString().slice(-8).toUpperCase();
const orderUrl = (order) => `${appUrl}/orders/${order._id}`;
const itemRows = (order) => order.items.map((item) => `<tr><td style="padding:10px 0;border-bottom:1px solid #eee;">${escapeHtml(item.name)}</td><td style="padding:10px 0;border-bottom:1px solid #eee;text-align:center;">${item.quantity}</td><td style="padding:10px 0;border-bottom:1px solid #eee;text-align:right;">₹${Number(item.price).toFixed(2)}</td></tr>`).join("");
const orderContent = (user, order, message, extra = "") => layout(`Order #${orderCode(order)}`, `<p>Hi ${escapeHtml(user.name)},</p><p>${escapeHtml(message)}</p><div style="background:#f8fafc;border-radius:8px;padding:16px;margin:20px 0;"><strong>Status:</strong> ${escapeHtml(order.status.replaceAll("_", " "))}<br/><strong>Payment:</strong> Cash on Delivery<br/><strong>Total:</strong> ₹${Number(order.totalAmount).toFixed(2)}</div><table style="width:100%;border-collapse:collapse;font-size:14px;"><thead><tr><th style="text-align:left;">Product</th><th>Qty</th><th style="text-align:right;">Price</th></tr></thead><tbody>${itemRows(order)}</tbody></table>${extra}<p style="margin-top:22px;">${button("View Order", orderUrl(order))}${button("Track Order", orderUrl(order))}</p>`);

const otpEmail = (user, otp, purpose) => ({ subject: purpose === "signup" ? `Your ${brand} verification code is ${otp}` : `Your ${brand} password reset code`, html: layout(purpose === "signup" ? `Welcome to ${brand}` : `Secure your ${brand} account`, `<p>Hi ${escapeHtml(user.name || "there")},</p><p>Your verification code is:</p><div style="font-size:32px;letter-spacing:8px;font-weight:700;text-align:center;padding:18px;color:#2575FC;">${escapeHtml(otp)}</div><p>This code expires in 10 minutes. Please do not share it with anyone.</p><p>If you did not request this code, you can safely ignore this email.</p>`) });
const welcomeEmail = (user) => ({ subject: `Welcome to ${brand}, ${user.name}!`, html: layout(`Welcome to ${brand}!`, `<p>Hi ${escapeHtml(user.name)},</p><p>Your account has been successfully created. We are excited to have you with us.</p><p>${button("Shop Now", appUrl)}</p>`) });
const orderEmail = (user, order, eventType) => { const messages = { placed: "Thank you for shopping with us. Your order has been successfully placed.", confirmed: "Your order has been confirmed and is now in our fulfilment queue.", processing: "Your order is now being prepared.", packed: "Your order has been packed and is ready to leave our facility.", shipped: "Your order is on its way.", out_for_delivery: "Your order is out for delivery today.", delivered: "Your order has been delivered. We hope you enjoy it!", delivery_failed: "We were unable to deliver your order. Please contact support for the next steps.", cancelled: "Your order has been cancelled." }; const extra = order.trackingNumber ? `<p><strong>${escapeHtml(order.courierName || "Courier")}:</strong> ${escapeHtml(order.trackingNumber)}</p>` : ""; return { subject: `${messages[eventType] || "Order update"} #${orderCode(order)}`, html: orderContent(user, order, messages[eventType] || `Your order status is now ${eventType}.`, extra) }; };
const returnEmail = (user, order) => ({ subject: `Return update for order #${orderCode(order)}`, html: orderContent(user, order, `Your return request is now ${order.return.status}.${order.return.reason ? ` Reason: ${order.return.reason}` : ""}`) });

module.exports = { escapeHtml, otpEmail, welcomeEmail, orderEmail, returnEmail };